import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,



  
}: {
  children: React.ReactNode
  
}) {
  return (
    <html lang="en">
      <body>
      {/* ===============================NAV BAR ============================= */}
<div className="wrapper">
  <div className="menu flex justify-left">
    <a href="/" className="active">Home</a>
    <a href="/flex">Flex</a>
    <a href="/grid">Grid</a>
    
  </div>
</div>
{/* ===============================NAV BAR ============================= */}
{children}
      </body>
    </html>
  )
}